image: node:12.4.0

pipelines:
  default:
    - step:
        script:
          - npm install 
          - npm -g install gulp
          - gulp build
  branches:
    master:
      - step:
         name: Clone
         deployment: production
         script:
           - npm install
           - npm -g install gulp
           - gulp build
    dev:
      - step:
          name: Clone
          deployment: test
          script:
            - npm install
            - npm -g install gulp
            - gulp build